# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Michael Mogenson
tagline:             
url:                 http://mogenson.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Michael Mogenson
  url:               http://mogenson.github.io
  email:             michael.mogenson@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/mogenson/mogenson.github.io

pages_list:
  About: '/about'
  Archive: '/archive'