# Site settings
baseurl = "https://mogenson.github.io/amycrafts/"
languageCode = "en-us"
title = "Amy Crafts"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "Amy Crafts"
    subtitle = "A collection of crafts projects by Amy Valera"

    # Body background color
    bodybgcolor = "#f9f9f9"
    #bodybgcolor = "#b4eee3"

    # Preview container button text
    buttontext = "Contact Me"

    # Footer text
    footertext = "Made by [Amy Valera](mailto:amyvalera@gmail.com \"Send me an email\") with a little bit of help from [Mike Mogenson](https://github.com/mogenson/amycrafts \"View Website Source\")"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
