# Site settings
baseurl = "https://mogenson.github.io/amycrafts/"
languageCode = "en-us"
title = "Amy Crafts"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"

[params]
    # Meta
    title = "Amy Crafts"
    subtitle = "A collection of crafts projects by Amy Valera"
    author = "Amy Valera"
    description = "Crafting portfolio for Amy Valera."
    keywords = "craft, crafts, crafting, crochet, crocheted, sew, sewing, sewed, knit, knitting, diy, homemade"

    # Body background color
    #bodybgcolor = "#f9f9f9"
    bodybgcolor = "#b4eee3"

    # Preview container button text
    buttontext = "Contact Me"

    # Footer text
    footertext = "Made by [Amy Valera](mailto:amyvalera@gmail.com \"Send me an email\")"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
